// <auto-generated />
namespace guestNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Identityabstractclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Identityabstractclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201407292157169_Identity abstract class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
